order = [ "cpu_load", "network", "backlight", "audio", "battery", "time" ]
separator = " | "

[cpu_load]
template = "  {CL15/NPROC*100}%"
update_interval = 30

[network]
no_value = "󰤮"
template = "{IPv4}"

[backlight]
device = "intel_backlight"
template = "{ICO} {BL}%"
icons = [ "󰃞", "󰃟", "󰃠" ]

[audio]
control = "Master"
mute = ""
template = "{ICO} {VOL}%"
icons = [ "", "", "" ]

[battery]
charging = ""
discharging = ""
enable_notifier = true
no_battery = "󱉞"
notifier_critical = 10
notifier_levels = [ 5, 8, 10, 15, 20 ]
separator = " "
icons = [ "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹" ]

[time]
format = "󰃭 %a, %b %d %H:%M "
update_seconds = false
