# Window-specific animation scripts.
# See `https://picom.app/#_animations` for animation options.

animations = (
  {
    triggers = [ "open" ];
    preset = "appear";
    scale = 1.0;
    duration = 1.0;
  },
  {
    triggers = [ "close" ];
    preset = "disappear";
    scale = 0.5;
    duration = 1.0;
  },
  {
    triggers = [ "show" ];
    preset = "fly-in";
    direction = "up";
    duration = 1.0;
  },
  {
    triggers = [ "hide" ];
    preset = "fly-out";
    direction = "down";
    duration = 1.0;
  },
  {
    triggers = [ "size", "position" ];
    preset = "geometry-change";
    duration = 0.5;
  },
)

