# picom: A compositor for X11
# ---------------------------------------
# Documentation for picom configurations:
# https://picom.app/

### PICOM CONFIGURATION ###

# SHADOWS
shadow = true;
shadow-radius = 7;
shadow-opacity = .75;
shadow-offset-x = -7;
shadow-offset-y = -7;

# FADING
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
# no-fading-openclose = false

# Opacity
frame-opacity = 1.0;
# inactive-dim-fixed = true

# CORNERS
corner-radius = 20;

# BLUR
blur-method = "dual_kawase";
blur-strength = 5;
blur-kern = "3x3box";
blur-background = true;
# blur-background-frame = true
blur-background-fixed = true;

# GENERAL SETTINGS
backend = "glx";
vsync = true;
dithered-present = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-client-leader = true;
detect-transient = true;
use-ewmh-active-win = true;
use-damage = true;
xrender-sync-fence = true
# window-shader-fg = "default"
# force-win-blend = false
# transparent-clipping = false
log-level = "warn";
# log-file = "/path/to/your/log/file"

# @include "rules.conf"
# @include "animations.conf"
