#################################
#             RULES             #
#################################
# Rule-based per-window options.
# See `https://picom.app/#_window_rules` for window-specific options.

rules: (
  {
    match = "focused";
    opacity = 0.95;
  },
  {
    match = "!focused";
    opacity = 0.8;
  },
  {
    match = "tooltip";
    fade = true;
    shadow = true;
    opacity = 0.8;
    focus = true;
    full-shadow = false;
  },
  {
    match = "popup_menu";
    opacity = 0.9;
  },
  {
    match = "dropdown_menu";
    opacity = 0.9;
  },
)

